#!/data/data/com.termux/files/usr/bin/sh
# svlogd target for OpenList. Rotates within $LOG_DIR.

HOME_DIR="${HOME:-/data/data/com.termux/files/home}"
LOG_DIR="$HOME_DIR/Openlist/data/log/sv"

mkdir -p "$LOG_DIR"
exec svlogd -tt "$LOG_DIR"
