#!/data/data/com.termux/files/usr/bin/sh
# svlogd target for aria2.

HOME_DIR="${HOME:-/data/data/com.termux/files/home}"
LOG_DIR="$HOME_DIR/aria2/log/sv"

mkdir -p "$LOG_DIR"
exec svlogd -tt "$LOG_DIR"
